LIME-633 Fix typo in banner.njk (cookieBannerAccept/cookieBannerReject)
alphagov/di-ipv-cri-common-express pull request #211
Opened 2023-05-18 12:40 UTC by smsgds

## Proposed changes

### What changed

Correct a typo in banner.njk (cookieBannerAccept/cookieBannerReject)

### Why did it change

Missing text in Driving License/Passport-v1 fronts was traced to a typo that had been replicated though existing CRI front ends.

### Issue tracking

- [LIME-633](https://govukverify.atlassian.net/browse/LIME-633)

2023-05-19 08:59 UTC, merlinc requested changes
Ah, yeah, it's not an immediate breaking change if the version number changes! :brain: 

Can you separate out the release of the new version from the PR? It's easier to understand releasing a new version separately to adding changes - I'll make a PR for the README to describe the release procedure.

Once this is merged, can you take a look at Derren's PRs - one of them I think is the change you've made, the other a similar UX type bug

https://github.com/alphagov/di-ipv-cri-common-express/pull/166/files
https://github.com/alphagov/di-ipv-cri-common-express/pull/167/files

Once that's done we can make a release.

2023-05-22 09:28 UTC, smsgds commented
> Ah, yeah, it's not an immediate breaking change if the version number changes! 🧠
> 
> Can you separate out the release of the new version from the PR? It's easier to understand releasing a new version separately to adding changes - I'll make a PR for the README to describe the release procedure.
> 
> Once this is merged, can you take a look at Derren's PRs - one of them I think is the change you've made, the other a similar UX type bug
> 
> https://github.com/alphagov/di-ipv-cri-common-express/pull/166/files https://github.com/alphagov/di-ipv-cri-common-express/pull/167/files
> 
> Once that's done we can make a release.

The changes on Derren’s first PR are identical to the changes on this one so I’ve opted to use his. The branch is pulled into this one and rebased to main, then the two commits on the second pr, where then cherry-picked into this one (to avoid an unneeded merge commit).

2023-05-22 09:42 UTC, merlinc approved these changes

2023-05-22 09:42 UTC, merlinc approved these changes

2023-05-22 10:00 UTC, merged